/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ScanDrawingIdRouteImport } from './routes/scan.$drawingId'
import { Route as HandoverProjectIdRouteImport } from './routes/handover.$projectId'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated.dashboard'
import { Route as AuthenticatedProjectsIndexRouteImport } from './routes/_authenticated.projects.index'
import { Route as ScanDrawingIdRevisionIdRouteImport } from './routes/scan.$drawingId.$revisionId'
import { Route as AuthenticatedProjectsProjectIdRouteImport } from './routes/_authenticated.projects.$projectId'
import { Route as AuthenticatedProjectsProjectIdIndexRouteImport } from './routes/_authenticated.projects.$projectId.index'
import { Route as AuthenticatedProjectsProjectIdSettingsRouteImport } from './routes/_authenticated.projects.$projectId.settings'
import { Route as AuthenticatedProjectsProjectIdIssuesRouteImport } from './routes/_authenticated.projects.$projectId.issues'
import { Route as AuthenticatedProjectsProjectIdDrawingsDrawingIdRouteImport } from './routes/_authenticated.projects.$projectId.drawings.$drawingId'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ScanDrawingIdRoute = ScanDrawingIdRouteImport.update({
  id: '/scan/$drawingId',
  path: '/scan/$drawingId',
  getParentRoute: () => rootRouteImport,
} as any)
const HandoverProjectIdRoute = HandoverProjectIdRouteImport.update({
  id: '/handover/$projectId',
  path: '/handover/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProjectsIndexRoute =
  AuthenticatedProjectsIndexRouteImport.update({
    id: '/projects/',
    path: '/projects/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const ScanDrawingIdRevisionIdRoute = ScanDrawingIdRevisionIdRouteImport.update({
  id: '/$revisionId',
  path: '/$revisionId',
  getParentRoute: () => ScanDrawingIdRoute,
} as any)
const AuthenticatedProjectsProjectIdRoute =
  AuthenticatedProjectsProjectIdRouteImport.update({
    id: '/projects/$projectId',
    path: '/projects/$projectId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProjectsProjectIdIndexRoute =
  AuthenticatedProjectsProjectIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedProjectsProjectIdRoute,
  } as any)
const AuthenticatedProjectsProjectIdSettingsRoute =
  AuthenticatedProjectsProjectIdSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedProjectsProjectIdRoute,
  } as any)
const AuthenticatedProjectsProjectIdIssuesRoute =
  AuthenticatedProjectsProjectIdIssuesRouteImport.update({
    id: '/issues',
    path: '/issues',
    getParentRoute: () => AuthenticatedProjectsProjectIdRoute,
  } as any)
const AuthenticatedProjectsProjectIdDrawingsDrawingIdRoute =
  AuthenticatedProjectsProjectIdDrawingsDrawingIdRouteImport.update({
    id: '/drawings/$drawingId',
    path: '/drawings/$drawingId',
    getParentRoute: () => AuthenticatedProjectsProjectIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/handover/$projectId': typeof HandoverProjectIdRoute
  '/scan/$drawingId': typeof ScanDrawingIdRouteWithChildren
  '/projects/$projectId': typeof AuthenticatedProjectsProjectIdRouteWithChildren
  '/scan/$drawingId/$revisionId': typeof ScanDrawingIdRevisionIdRoute
  '/projects/': typeof AuthenticatedProjectsIndexRoute
  '/projects/$projectId/issues': typeof AuthenticatedProjectsProjectIdIssuesRoute
  '/projects/$projectId/settings': typeof AuthenticatedProjectsProjectIdSettingsRoute
  '/projects/$projectId/': typeof AuthenticatedProjectsProjectIdIndexRoute
  '/projects/$projectId/drawings/$drawingId': typeof AuthenticatedProjectsProjectIdDrawingsDrawingIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/handover/$projectId': typeof HandoverProjectIdRoute
  '/scan/$drawingId': typeof ScanDrawingIdRouteWithChildren
  '/scan/$drawingId/$revisionId': typeof ScanDrawingIdRevisionIdRoute
  '/projects': typeof AuthenticatedProjectsIndexRoute
  '/projects/$projectId/issues': typeof AuthenticatedProjectsProjectIdIssuesRoute
  '/projects/$projectId/settings': typeof AuthenticatedProjectsProjectIdSettingsRoute
  '/projects/$projectId': typeof AuthenticatedProjectsProjectIdIndexRoute
  '/projects/$projectId/drawings/$drawingId': typeof AuthenticatedProjectsProjectIdDrawingsDrawingIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/handover/$projectId': typeof HandoverProjectIdRoute
  '/scan/$drawingId': typeof ScanDrawingIdRouteWithChildren
  '/_authenticated/projects/$projectId': typeof AuthenticatedProjectsProjectIdRouteWithChildren
  '/scan/$drawingId/$revisionId': typeof ScanDrawingIdRevisionIdRoute
  '/_authenticated/projects/': typeof AuthenticatedProjectsIndexRoute
  '/_authenticated/projects/$projectId/issues': typeof AuthenticatedProjectsProjectIdIssuesRoute
  '/_authenticated/projects/$projectId/settings': typeof AuthenticatedProjectsProjectIdSettingsRoute
  '/_authenticated/projects/$projectId/': typeof AuthenticatedProjectsProjectIdIndexRoute
  '/_authenticated/projects/$projectId/drawings/$drawingId': typeof AuthenticatedProjectsProjectIdDrawingsDrawingIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/handover/$projectId'
    | '/scan/$drawingId'
    | '/projects/$projectId'
    | '/scan/$drawingId/$revisionId'
    | '/projects/'
    | '/projects/$projectId/issues'
    | '/projects/$projectId/settings'
    | '/projects/$projectId/'
    | '/projects/$projectId/drawings/$drawingId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/handover/$projectId'
    | '/scan/$drawingId'
    | '/scan/$drawingId/$revisionId'
    | '/projects'
    | '/projects/$projectId/issues'
    | '/projects/$projectId/settings'
    | '/projects/$projectId'
    | '/projects/$projectId/drawings/$drawingId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_authenticated/dashboard'
    | '/handover/$projectId'
    | '/scan/$drawingId'
    | '/_authenticated/projects/$projectId'
    | '/scan/$drawingId/$revisionId'
    | '/_authenticated/projects/'
    | '/_authenticated/projects/$projectId/issues'
    | '/_authenticated/projects/$projectId/settings'
    | '/_authenticated/projects/$projectId/'
    | '/_authenticated/projects/$projectId/drawings/$drawingId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  HandoverProjectIdRoute: typeof HandoverProjectIdRoute
  ScanDrawingIdRoute: typeof ScanDrawingIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scan/$drawingId': {
      id: '/scan/$drawingId'
      path: '/scan/$drawingId'
      fullPath: '/scan/$drawingId'
      preLoaderRoute: typeof ScanDrawingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/handover/$projectId': {
      id: '/handover/$projectId'
      path: '/handover/$projectId'
      fullPath: '/handover/$projectId'
      preLoaderRoute: typeof HandoverProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/projects/': {
      id: '/_authenticated/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof AuthenticatedProjectsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/scan/$drawingId/$revisionId': {
      id: '/scan/$drawingId/$revisionId'
      path: '/$revisionId'
      fullPath: '/scan/$drawingId/$revisionId'
      preLoaderRoute: typeof ScanDrawingIdRevisionIdRouteImport
      parentRoute: typeof ScanDrawingIdRoute
    }
    '/_authenticated/projects/$projectId': {
      id: '/_authenticated/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/projects/$projectId/': {
      id: '/_authenticated/projects/$projectId/'
      path: '/'
      fullPath: '/projects/$projectId/'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdIndexRouteImport
      parentRoute: typeof AuthenticatedProjectsProjectIdRoute
    }
    '/_authenticated/projects/$projectId/settings': {
      id: '/_authenticated/projects/$projectId/settings'
      path: '/settings'
      fullPath: '/projects/$projectId/settings'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdSettingsRouteImport
      parentRoute: typeof AuthenticatedProjectsProjectIdRoute
    }
    '/_authenticated/projects/$projectId/issues': {
      id: '/_authenticated/projects/$projectId/issues'
      path: '/issues'
      fullPath: '/projects/$projectId/issues'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdIssuesRouteImport
      parentRoute: typeof AuthenticatedProjectsProjectIdRoute
    }
    '/_authenticated/projects/$projectId/drawings/$drawingId': {
      id: '/_authenticated/projects/$projectId/drawings/$drawingId'
      path: '/drawings/$drawingId'
      fullPath: '/projects/$projectId/drawings/$drawingId'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdDrawingsDrawingIdRouteImport
      parentRoute: typeof AuthenticatedProjectsProjectIdRoute
    }
  }
}

interface AuthenticatedProjectsProjectIdRouteChildren {
  AuthenticatedProjectsProjectIdIssuesRoute: typeof AuthenticatedProjectsProjectIdIssuesRoute
  AuthenticatedProjectsProjectIdSettingsRoute: typeof AuthenticatedProjectsProjectIdSettingsRoute
  AuthenticatedProjectsProjectIdIndexRoute: typeof AuthenticatedProjectsProjectIdIndexRoute
  AuthenticatedProjectsProjectIdDrawingsDrawingIdRoute: typeof AuthenticatedProjectsProjectIdDrawingsDrawingIdRoute
}

const AuthenticatedProjectsProjectIdRouteChildren: AuthenticatedProjectsProjectIdRouteChildren =
  {
    AuthenticatedProjectsProjectIdIssuesRoute:
      AuthenticatedProjectsProjectIdIssuesRoute,
    AuthenticatedProjectsProjectIdSettingsRoute:
      AuthenticatedProjectsProjectIdSettingsRoute,
    AuthenticatedProjectsProjectIdIndexRoute:
      AuthenticatedProjectsProjectIdIndexRoute,
    AuthenticatedProjectsProjectIdDrawingsDrawingIdRoute:
      AuthenticatedProjectsProjectIdDrawingsDrawingIdRoute,
  }

const AuthenticatedProjectsProjectIdRouteWithChildren =
  AuthenticatedProjectsProjectIdRoute._addFileChildren(
    AuthenticatedProjectsProjectIdRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedProjectsProjectIdRoute: typeof AuthenticatedProjectsProjectIdRouteWithChildren
  AuthenticatedProjectsIndexRoute: typeof AuthenticatedProjectsIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedProjectsProjectIdRoute:
    AuthenticatedProjectsProjectIdRouteWithChildren,
  AuthenticatedProjectsIndexRoute: AuthenticatedProjectsIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface ScanDrawingIdRouteChildren {
  ScanDrawingIdRevisionIdRoute: typeof ScanDrawingIdRevisionIdRoute
}

const ScanDrawingIdRouteChildren: ScanDrawingIdRouteChildren = {
  ScanDrawingIdRevisionIdRoute: ScanDrawingIdRevisionIdRoute,
}

const ScanDrawingIdRouteWithChildren = ScanDrawingIdRoute._addFileChildren(
  ScanDrawingIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  HandoverProjectIdRoute: HandoverProjectIdRoute,
  ScanDrawingIdRoute: ScanDrawingIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
